name: Deploy Weather API to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: intrepid-period-461115-b6

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV }}" > .env

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/intrepid-period-461115-b6/weather-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy weather-api \
            --image gcr.io/intrepid-period-461115-b6/weather-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars="API_KEY=${{ secrets.API_KEY }}"
            --port 8080 \
            --memory 256Mi
